### ISSUE TITLE
Installation path includes buildroot

### ISSUE THREAD

**Issue by lgbaldoni** [michaelrsweet/lprint#10]
As per subject, Makefile.in contains
```
BUILDROOT       =       $(DSTROOT)$(RPM_BUILD_ROOT)$(DESTDIR)
```
which complicates packaging.

autoreconf also [fails](https://github.com/michaelrsweet/lprint/files/4096511/lprint_autoreconf.txt).

Using openSUSE Tumbleweed.

**Comment by michaelrsweet** [comment]
NEVER run autoreconf or other autotools - they produce non-portable makefiles and header files, so I always create those by hand and only use autoconf to produce a standalone configure script. Running autoreconf will only break the build files I've worked hard to prepare.

As for defining BUILDROOT, that is an attempt to support the various "standard" install prefix variables in use (DSTROOT on macOS, RPM_BUILD_ROOT for RPM builds, DESTDIR for GNU builds) with a single variable since nobody wants to be happy.

I was unaware that SuSE used BUILDROOT in any way - they are RPM-based and should be using RPM_BUILD_ROOT, right? And that will get auto-substituted as the value of BUILDROOT, right? What is the problem? What errors are you seeing?

**Comment by lgbaldoni** [comment]
The problem arises during the install:
```
make install DESTDIR=/home/abuild/rpmbuild/BUILDROOT/lprint-1.0b1-0.x86_64
```
installs e.g. lprint in:
```
/home/abuild/rpmbuild/BUILDROOT/lprint-1.0b1-0.x86_64/home/abuild/rpmbuild/BUILDROOT/lprint-1.0b1-0.x86_64/usr/bin/lprint
```

I have to use this [patch](https://github.com/michaelrsweet/lprint/files/4097557/lprint-installation_path.patch.txt). I could of course just omit the DESTDIR variable not using the regular build macros, but that doesn't look very standard.

**Comment by michaelrsweet** [comment]
@lgbaldoni DESTDIR is the GNU prefix. RPM_BUILD_ROOT will already be set to that value...

I'm not sure what macros you are using, but "make install" is all you need for this project.
