### ISSUE TITLE
Printers always exposed publicly?

### ISSUE THREAD

**Issue by gjoseph92** [michaelrsweet/lprint#101]
Regardless of the settings for `listen-hostname` or `server-hostname`, it seems that printers are always exposed to the local network. I've tried `127.0.0.1` and `localhost` for both, but an iPhone on the same local network can still access the printers via IPP. (`listen-hostname=localhost` at least makes the web interface only accessible locally, but the printers are still exposed.) How would you make `lprint server` only accept connections from localhost?

Similarly, I notice that when installing from the package on macOS, the launchd service makes both the web interface and printers publicly accessible. From a security perspective, this doesn't seem like an ideal default?

**Comment by michaelrsweet** [comment]
In answer to your specific question, using "-o listen-hostname=localhost -o server-hostname=localhost" should be sufficient to limit network access to the local system, although it won't limit the DNS-SD registrations to the loopback interface - that's a [PAPPL bug](https://github.com/michaelrsweet/pappl/issues/274).

In general, running the "server" sub-command starts an IP service while just letting the service auto-start just uses the local domain socket for standalone operation - this effectively makes it unavailable for printing from applications which is why the macOS package starts it via launchd. Defaulting to localhost-only probably makes sense here, but I also want to make sure there is an easy way to allow for sharing on the local network since that is also a common use case... :)

**Comment by michaelrsweet** [comment]
So the PAPPL bug is fixed, but still looking at how to specifically support/document this for the packages binaries.

**Comment by michaelrsweet** [comment]
[master bcb152c] Update docos about config files and the listen hostname option.
