### ISSUE TITLE
Seiko Label Printer and Debian

### ISSUE THREAD

**Issue by kalpha2** [michaelrsweet/lprint#133]
if i use the `lprint drivers` using package in debian11 it shows me dymo, pwg, zpl are any of these meant for use with Seiko SLP ?
Or is there other steps to install and make use of?
I pulled source to build but lpappl will not build because of version of CUPS in Deb11 is only v2.3.3 is there a version of lpappl that is compatible with that?
If I do build will that be sufficient to get SLP option or do I need to get a ppd or ilk to configure or make it work?
fyi I have an SLP100 working via CUPS on Deb11 ... except it always misses some characters, it used to be the left hand side of label but I tweak to print 180degrees but now it loses characters on right hand side when lots of text supplied.

**Comment by michaelrsweet** [comment]
@kalpha2 As the SEIKO drivers are still alpha-quality, they are not enabled by default.

In order to use recent PAPPL and LPrint releases, you *do* need a recent version of CUPS and 2.3.3 is definitely not recent enough. You can try building the snap locally and change the build commands to add the `--enable-experimental` configure option, and that will work around the old version of CUPS on your main system image, but like I said the SEIKO drivers have known issues so I don't know whether they will work for you or resolve the problems you have with the current drivers you are using...
