### ISSUE TITLE
Improve server-mode documentation

### ISSUE THREAD

**Issue by brianbarr** [michaelrsweet/lprint#53]
Would it be possible to clearly document how to configure lprint as a autostart server daemon with an example ? 

I would imagine many users of this software would be installing it on an inexpensive device such as a raspberry pi to create "airprint" enabled label printers. The docs describing the server functionality currently don't clearly show how to do this. If you run "lprint server" you have a process that is still attached to the initiating shell, not a background server.

**Comment by michaelrsweet** [comment]
@brianbarr There is already a section in the documentation file about running as a server, and if you install from source or use the macOS package the systemd/launchd service files are already bundled to make this happen "automatically".

I am also testing some snap changes to get *it* to run a server by default since the whole permissions thing seems to be a problem... :/

Anyways, I'll see if I can talk more about this, but I'm hoping it will soon be a non-issue for most people... :)

**Comment by brianbarr** [comment]
Just a suggestion to put an example of using the "lprint server...." command in the docs. The docs reference the server subcommand .. and the examples are don't have the command in there .. like this:

lprint server -o server-port=699  ; starts up an lprint server instance listening on port 699

How to easily daemonize lprint after a snap installation ?

**Comment by brianbarr** [comment]
also in the docs under "server web interface" the example looks incorrect as the server subcommand is missing 

lprint -o server-name=HOSTNAME -o server-port=NNN -o auth-service=cups

Should it read "lprint server o server-name=HOSTNAME -o server-port=NNN -o auth-service=cups" ??

**Comment by michaelrsweet** [comment]
@brianbarr Yes, you need the "lprint server" on the front...

**Comment by michaelrsweet** [comment]
OK, this is fixed in the documentation now...
